---
parser: babel-eslint
extends:
  - es/2015/server
plugins:
- babel
- markdown
env:
  es6: true
  node: true
  mocha: true
parserOptions:
  sourceType: 'module'
  ecmaVersion: 2017
  ecmaFeatures:
    accessor-pairs: 2
    arrowFunctions: true
    binaryLiterals: true
    blockBindings: true
    classes: true
    defaultParams: true
    destructuring: true
    experimentalObjectRestSpread: true
    forOf: true
    generators: true
    globalReturn: true
    jsx: true
    modules: true
    objectLiteralComputedProperties: true
    objectLiteralDuplicateProperties: true
    objectLiteralShorthandMethods: true
    objectLiteralShorthandProperties: true
    octalLiterals: true
    regexUFlag: true
    regexYFlag: true
    restParams: true
    spread: true
    superInFunctions: true
    templateStrings: true
    unicodeCodePointEscapes: true
rules:
  arrow-parens:
  - 2
  - as-needed
  array-bracket-spacing:
  - 2
  - never
  block-scoped-var: 2
  brace-style:
  - 2
  - 1tbs
  - allowSingleLine: true
  camelcase:
  - 2
  - properties: always
  comma-dangle: [2, 'never']
  comma-spacing: 0
  comma-style:
  - 2
  - last
  complexity: [1, 9]
  computed-property-spacing:
  - 2
  - never
  consistent-return: 0
  consistent-this: 0
  curly:
  - 2
  - all
  default-case: 2
  dot-location:
  - 2
  - property
  dot-notation: 2
  eol-last: 2
  eqeqeq: 2
  func-names: 0
  func-style: 0
  global-require: 2
  generator-star-spacing:
  - 2
  - before: true
    after: false
  guard-for-in: 2
  handle-callback-err:
  - 2
  - error
  id-length: 0
  id-match:
  - 2
  - "^(?:_?[a-zA-Z0-9]*)|[_A-Z0-9]+$"
  indent:
  - 2
  - 2
  - SwitchCase: 1
  init-declarations: 0
  key-spacing:
  - 2
  - beforeColon: false
    afterColon: true
  linebreak-style: 2
  lines-around-comment: 0
  max-depth: 0
  max-len:
  - 2
  - ignoreTemplateLiterals: true
    ignoreStrings: true
  max-nested-callbacks: 0
  max-params: 0
  max-statements: 0
  new-cap: 0
  new-parens: 2
  newline-after-var: 0
  no-alert: 2
  no-array-constructor: 2
  no-bitwise: 0
  no-caller: 2
  no-case-declarations: 2
  no-catch-shadow: 2
  no-class-assign: 2
  no-cond-assign: 2
  no-console: 0
  no-const-assign: 2
  no-constant-condition: 2
  no-continue: 0
  no-control-regex: 2
  no-debugger: 2
  no-delete-var: 2
  no-div-regex: 2
  no-dupe-args: 2
  no-dupe-keys: 2
  no-duplicate-case: 2
  no-else-return: 2
  no-empty: 2
  no-empty-pattern: 2
  no-empty-character-class: 2
  no-eq-null: 2
  no-eval: 2
  no-ex-assign: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-extra-boolean-cast: 2
  no-extra-parens: [ 2, 'all', { nestedBinaryExpressions: false }]
  no-extra-semi: 2
  no-fallthrough: 2
  no-floating-decimal: 2
  no-func-assign: 2
  no-implicit-coercion: 2
  no-implied-eval: 2
  no-inline-comments: 0
  no-inner-declarations:
  - 2
  - functions
  no-invalid-regexp: 2
  no-invalid-this: 0
  no-irregular-whitespace: 2
  no-iterator: 2
  no-label-var: 2
  no-labels: 2
  no-lone-blocks: 2
  no-lonely-if: 2
  no-loop-func: 2
  no-mixed-requires:
  - 2
  - true
  no-mixed-spaces-and-tabs: 2
  no-multi-spaces: 2
  no-multi-str: 2
  no-multiple-empty-lines: 0
  no-native-reassign: 2
  no-negated-in-lhs: 2
  no-nested-ternary: 0
  no-new: 2
  no-new-func: 2
  no-new-object: 2
  no-new-require: 2
  no-new-wrappers: 2
  no-obj-calls: 2
  no-octal: 2
  no-octal-escape: 2
  no-param-reassign: 2
  no-path-concat: 2
  no-plusplus: 0
  no-process-env: 0
  no-process-exit: 0
  no-proto: 2
  no-redeclare: 2
  no-regex-spaces: 2
  no-restricted-modules: 0
  no-return-assign: 2
  no-script-url: 2
  no-self-compare: 2
  no-sequences: 2
  no-shadow: 2
  no-shadow-restricted-names: 2
  no-spaced-func: 2
  no-sparse-arrays: 2
  no-sync: 0
  no-ternary: 0
  no-this-before-super: 2
  no-throw-literal: 2
  no-trailing-spaces: 2
  no-undef: 2
  no-undef-init: 2
  no-undefined: 0
  no-underscore-dangle: 0
  no-unexpected-multiline: 2
  no-unneeded-ternary: 2
  no-unreachable: 2
  no-unused-expressions: 2
  no-unused-vars:
  - 2
  - vars: all
    args: after-used
  no-use-before-define: 0
  no-useless-call: 2
  no-var: 2
  no-void: 2
  no-warning-comments: 0
  no-with: 2
  object-curly-spacing:
  - 0
  - always
  object-shorthand:
  - 2
  - always
  one-var:
  - 2
  - never
  operator-assignment:
  - 2
  - always
  operator-linebreak:
  - 2
  - after
  padded-blocks: [2, 'never']
  prefer-const: 2
  prefer-reflect: 0
  prefer-spread: 2
  quote-props:
  - 2
  - as-needed
  quotes:
  - 2
  - single
  - avoidEscape: true
  radix: 2
  require-yield: 2
  semi:
  - 2
  - always
  semi-spacing:
  - 2
  - before: false
    after: true
  sort-vars: 0
  keyword-spacing:
  - 2
  - before: true
    after: true
  space-before-blocks:
  - 2
  - always
  space-before-function-paren:
  - 2
  - anonymous: never
    named: never
  space-in-parens: 0
  space-infix-ops:
  - 2
  - int32Hint: false
  space-unary-ops:
  - 2
  - words: true
    nonwords: false
  spaced-comment:
  - 2
  - always
  strict: 0
  use-isnan: 2
  valid-jsdoc: 2
  valid-typeof: 2
  vars-on-top: 0
  wrap-iife: 2
  wrap-regex: 0
  yoda:
  - 2
  - never
  - exceptRange: true
  newline-per-chained-call: 0
  class-methods-use-this: 0
  no-empty-function: 0
  sort-imports: [2, { memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single'], ignoreCase: true  }]
