Vagrant.configure(2) do |config|
  config.vm.define "meteor" do |meteor|
    config.vm.box = "ubuntu/trusty64"
    config.vm.network "private_network", ip: "172.27.1.100"
  end

  config.vm.define "mongo" do |mongo|
    config.vm.box = "ubuntu/trusty64"
    config.vm.network "private_network", ip: "172.27.1.101"
  end

  config.vm.define "proxy" do |proxy|
    config.vm.box = "ubuntu/trusty64"
    config.vm.network "private_network", ip: "172.27.1.102"
  end
end
