FROM mup-tests-server
RUN curl https://get.docker.com/ | sh && usermod -aG docker $(whoami) && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN echo 'DOCKER_OPTS="--storage-driver=vfs"' >> /etc/default/docker
